### ISSUE TITLE
release request for noetic

### ISSUE THREAD

**Issue by chikuta** [tork-a/rtctree-release#2]
I want to use this package via apt command to mainte our system in noetic.
Can you please release package for noetic ?

Please let me know if there is anything I can do for you like python3 portng.

**Comment by Tomohiro-Chaki-Honda** [comment]
@k-okada san
I got same porblem as @chikuta san.
It would be appreciate if you could release the package for noetic.

**Comment by k-okada** [comment]
Sorry for late, I have released just 2 weeks ago https://github.com/ros/rosdistro/pull/38675.
Currently it is only available on testing repository (https://wiki.ros.org/TestingRepository), so please wait for next sync (c.f https://discourse.ros.org/t/new-packages-for-noetic-2023-10-12/34108 )

**Comment by Tomohiro-Chaki-Honda** [comment]
Thank you so much.

**Comment by chikuta** [comment]
Thank you.
